# -*- coding: utf-8 -*-
"""Shop Plants

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13xTcmiNUX0dYm0zSFKkFYt1c_g_u-12n
"""

import numpy as np
import pandas as pd
import gc

"""# Class ShopPlants"""

class ShopPlants:

  In = ['soil', 0, 50, 'type']   #Input container
  clean_data = None

  #CONSTRUCTOR to create clean_data DataFrame 
  def __init__(self):
    data = pd.read_csv('Data.csv')
    x = data.iloc[:, [1,2,3,4,5]].values
    self.clean_data = pd.DataFrame(x, columns=['name', 'soil', 'Tmin', 'Tmax', 'type'])


  "___________________________________________________________________________________________________________________________________"
  #To take Soil input
  def chooseSoil(self, Ready):
    while Ready:
      Ready = False
      print("\n\nType of Soils - \n")
      print("\t1. Loamy \n\t2. Sandy  \n\t3. Clay  \n\t4. Silty \n\t5. Peaty")
      
      try:
        Soil = int(input("\n\nEnter the type of soil (number)  -   "))
        
        if Soil == 1:
          Soil = 'Loamy'

        elif Soil == 2:
          Soil = 'Sandy'

        elif Soil == 3:
          Soil = 'Clay'

        elif Soil == 4:
          Soil = 'Silty'

        elif Soil == 5:
          Soil = 'Peaty'
        
        else:
          print("Wrong Choice entered - Re-enter")
          Ready = True
      
      except ValueError:
        print("\n---------You have entered wrong type value -- Re-enter---------")
        Ready = True
    
    self.In[0] = Soil


  "___________________________________________________________________________________________________________________________________"
  #To take Temperature Input
  def chooseTempt(self, Ready):
    while Ready:  
      print("\n\nYour plant loves your atmosphere. Please tell us the temperature (Min and Max) around your area -  ")
      Ready = False
      try:  
        Tempt_min = float(input("\nMinimum -  "))
        Tempt_max = float(input("\nMaximum -  "))

        Tempt_min = int(round(Tempt_min))
        Tempt_max = int(round(Tempt_max))
      
      except ValueError:
        print("\n---------You have entered wrong type value -- Re-enter---------")
        Ready = True
    
    self.In[1] = Tempt_min
    self.In[2] = Tempt_max


  "___________________________________________________________________________________________________________________________________"
  #To take Plant type input
  def choosePlant(self, Ready): 
    while Ready:
      Ready = False  
      print("\nType of Plants - \n")
      print("\t1. Veg \n\t2. Fruits  \n\t3. Flowers  \n\t4. Crops")
      try:
        Type = int(input("\n\nEnter the type of Plants (number) -   "))

        if Type == 1:
          Type = 'Veg'

        elif Type == 2:
          Type = 'Fruits'

        elif Type == 3:
          Type = 'Flowers'

        elif Type == 4:
          Type = 'Crops'

        else:
          print("Wrong Choice entered - Re-enter")
          Ready = True
      
      except ValueError:
        print("\n---------You have entered wrong type value -- Re-enter---------")
        Ready = True  

    self.In[3] = Type

  "___________________________________________________________________________________________________________________________________"
  #See Input
  def checkInput(self):
    print("\n\nYour choices - ")
    for i in self.In:
      print("\n\t%s" %i)

    #print("\n\t{0}".format(i for i in self.In))
    print("\n\n")

  #To start the main process
  def Process(self):
    new_data = self.clean_data[self.clean_data['soil']== self.In[0]]
    new_data = new_data[new_data['type']== self.In[3]]
    new_data = new_data[new_data['Tmax']<= (self.In[2]+5)]
    new_data = new_data[(new_data['Tmin']-5)<= self.In[1]]
    result = list(new_data['name'])

    return result


"""# MAIN Function"""

if __name__ == '__main__':

  HALT = False
  while HALT is False:
    print("Do you want to buy some plants? We'll give you some excellent choices!!!")
    Name = input("Your Good Name -  ")

    obj = ShopPlants()
    print("___________________________________________________________________________________________________________________________________")
    obj.chooseSoil(True)
    print("___________________________________________________________________________________________________________________________________")
    obj.chooseTempt(True)
    print("___________________________________________________________________________________________________________________________________")
    obj.choosePlant(True)
    print("___________________________________________________________________________________________________________________________________")
    obj.checkInput()

    result = obj.Process()
  
    print("\n\nAs per your Wonderful choice {0}, we suggest you these plants -- ".format(Name))
    for i in result:
      print("\n=====>>>\t%s" %i)
    
    #print("\n\t%s" %i for i in result )

    print("\n\n -----------------Thanks for choosing us! -----------------")
    query = input("\nWant to try again? [y/n]")
    if query == 'n':
      print("\n\n -----------------SEE YOU NEXT TIME ^_^! -----------------")
      HALT = True

  gc.collect()